apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

#kubectl create namespace my-namespace
#kubectl config view
#kubectl config set-context --current --namespace=<namespace>
#kubectl get namespace
#kubectl config get-contexts